version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: !Ref task-def-number
        LoadBalancerInfo:
          ContainerName: !Ref container-app-name
          ContainerPort: 80
        PlatformVersion: "LATEST"